- name: user creation
  hosts: local
  connection: local
  become: yes
  # ignore_errors: true
  tasks:
  - name: check user exist or not
    ansible.builtin.command: id roboshop
    register: user_output
    ignore_errors: true

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ user_output }}"
# create user if user not exist
  - name: create user
    ansible.builtin.command: useradd roboshop
    when: user_output.rc != 0